-- Tabulka pro uživatelské profily, propojená s vestavěnou auth.users
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  email text,
  -- Role: 'user', 'admin'. Výchozí je 'user'.
  role text default 'user',
  -- Status: 'pending', 'approved'. Výchozí je 'pending'.
  status text default 'pending'
);

-- Tabulka pro zprávy z kontaktního formuláře
create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false
);

-- Tabulka pro chat (nástěnku)
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text,
  -- Propojení s profilem autora
  user_id uuid references public.profiles on delete cascade
);

-- Tabulka pro dokumenty (název a odkaz na soubor ve Storage)
create table documents (
  id bigint generated by default as identity primary key,
  name text not null,
  file_path text not null,
  uploaded_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabulka pro kurzy (linky)
create table courses (
    id bigint generated by default as identity primary key,
    name text not null, -- Např. "Linka 15 - Ranní"
    description text,
    -- Cesty k fotkám ve Storage
    morning_photo_path text,
    afternoon_photo_path text
);